
stages:
 - lint
 - build
 - publish
 - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

Docker_Lint:
  image: docker:19.03.0-dind
  stage: lint
  script:
    - docker run --rm -i hadolint/hadolint < Dockerfile
  allow_failure: false

Docker_build-package:
  image: docker:20.10.16
  stage: build
  needs: [Docker_Lint] 
  script:
    - docker build --tag=python-api:1.0 . 
    - docker save -o python-api:1.0.tar python-api:1.0
  allow_failure: false

  cache: {}

  artifacts:
    paths:
      - python-api:1.0.tar
    expire_in: 1 week

Docker_Publish:
  image: docker:20.10.16
  stage: publish
  needs: [Docker_build-package]
  script:
    - echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin
    - docker image load < python-api:1.0.tar
    - docker tag python-api:1.0 $DOCKER_USER/python-api:1.0
    - docker push $DOCKER_USER/python-api:1.0

Terraform_Deploy:
  image: 
     name: hashicorp/terraform:light
     entrypoint: [""]

  stage: deploy
  needs: [Docker_Publish]
  script:
    - export TF_VAR_access_key=$access_key
    - export TF_VAR_secret_key=$secret_key
    - terraform init
    - terraform fmt
    - terraform plan
    - terraform apply -auto-approve